### ISSUE TITLE
Disconnect crash

### ISSUE THREAD

**Issue by CWBudde** [tbasse/fritzbox-callmonitor#5]
I am running this for 3 days continously, but it has crashed at least two times noe.

The latest one I catched in the console:

```
CallMonitor/node_modules/node-fritzbox-callmonitor/index.js:99
      self.call[data[2]].disconnect = data[0];
                                    ^

TypeError: Cannot set property 'disconnect' of undefined
    at Socket.<anonymous> (/Users/gabi/Library/CallMonitor/node_modules/node-fritzbox-callmonitor/index.js:99:37)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Cannot set property 'disconnect' of undefined
```

It would be nice if the script would not just crash, but just continue to run in some way.

**Comment by CWBudde** [comment]
It just happened again. Proposal:

Rewrite:

```
    if (data[1] === 'disconnect') {
      self.call[data[2]].disconnect = data[0];
      self.call[data[2]].duration   = parseInt(data[3], 10);

      var call = self.call[data[2]];
      delete(self.call[data[2]]);
      self.emit('disconnected', call);
      return;
```

to something like this (untested code, just out of my head):

```
    if (data[1] === 'disconnect') {
      var call = self.call[data[2]] ?? {};
      call.disconnect = data[0];
      call.duration   = parseInt(data[3], 10);
      self.emit('disconnected', call);
      return;
```

**Comment by CWBudde** [comment]
Eventually I was running the same script twice in parallel. This might have been the reason for the crash, but I'm not deep into the code to judge it.
